server:
  port: 8080

# 数据库相关配置:
# mySql8需要设置时区
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.86:3306/spring-test?serverTimezone=UTC
    username: spring-test
    password: 8KRLyN32HAtcxi5a

#spring:
#  datasource:
#    # druid写法2
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://39.105.108.80:3306/test_database?serverTimezone=UTC
#      username: test_database
#      password: yHKSmGWJztyP56Hi

# MP相关配置
mybatis-plus:
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/gtnes/mapper/xml/*.xml
  global-config:
    db-config:
      # 主键类型 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (idWorker)", 3:"全局唯一ID (UUID)"
      id-type: auto
      # 表名前缀
#      table-prefix: book_
      # 逻辑删除配置
#      logic-delete-field: deleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0
  configuration:
    # 开启MP日志 打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
