server:
  port: 8080

# 数据库相关配置:
# mySql8需要设置时区
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.108.80:3306/test_database?serverTimezone=UTC
    username: test_database
    password: yHKSmGWJztyP56Hi

# MP相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml